### ISSUE TITLE
Publish on mavenCentral

### ISSUE THREAD

**Issue by vanniktech** [ziggy42/kolor#6]
I'm using kolor through ktlint and I'd like to get rid of `jcenter()` in my project as every now and then it's flaky and dependencies can't be resolved properly.

Could you also publish kolor to mavenCentral?

AFAIK, you can also sync from jcenter / bintray to mavenCentral so it would not need any additional modifications.

**Comment by ziggy42** [comment]
Thanks for the input, will take a look soon :+1:

**Comment by vanniktech** [comment]
@ziggy42 is there any update? I can help with the migration.

**Comment by ziggy42** [comment]
Sorry I forgot about this :smile: I'll try to do it by the end of the week :slightly_smiling_face:

**Comment by ziggy42** [comment]
Sorry, I have to postpone it a bit. Something came up and I won't have time in the next few weeks to do it properly. I already started the process but a package name change is required and some other small things. I'd like to take some time to do it properly.

**Comment by vanniktech** [comment]
Alright. Thanks for letting us know.

**Comment by bolinfest** [comment]
According to https://jfrog.com/knowledge-base/why-should-i-use-jcenter-over-maven-central/:

> If you want to upload your library to Maven Central you could do it easily with a single click on the Bintray site.

I take it it's not actually that simple?

**Comment by vanniktech** [comment]
I no longer have a need for this as this got removed from ktlint - https://github.com/shyiko/ktlint/commit/8688b01f300c9187674f5948da9ff31fe5185561
